apiVersion: apps/v1
kind: Deployment
metadata:
  name: dyn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dyn
  template:
    metadata:
      labels:
        app: dyn
    spec:
      containers:
      - image: okteto.dev/dyn:latest
        name: dyn
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "1d18fdc8-96b0-4179-97eb-516180551437"
        - name: Vless_Path
          value: "/owxqb67"
        - name: Vmess_UUID
          value: "1d18fdc8-96b0-4179-97eb-516180551437"
        - name: Vmess_Path
          value: "/sejnft56"
        - name: Share_Path
          value: "/v2link"
